name: Bug report
description: Something is not working or is going wrong
labels: [ bug ]

body:
- type: checkboxes
  attributes:
    label: Preliminary checks
    options:
    - label: I have checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic
      required: true
    - label: I have checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds)
      required: true
- type: dropdown
  attributes:
    label: Platform
    description: Choose your platform
    options:
    - Windows
    - macOS
    - Linux
    - PlayStation Vita
    - Nintendo Switch
    - Other
  validations:
    required: true
- type: input
  attributes:
    label: Additional platform info
    placeholder: Describe your platform if you chose "Other" in the previous section.
- type: textarea
  attributes:
    label: Describe the bug
    placeholder: Provide a clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    placeholder: |
      Steps to reproduce the bug:
      1. Go to ...
      2. Click on ...
      3. See error ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    placeholder: Provide a clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    placeholder: >
      If possible, provide screenshots to illustrate the issue.
      You can add them by dragging and dropping the image file to this section.
- type: textarea
  attributes:
    label: Save file
    placeholder: >
      If possible, provide a save file to make it easier for developers to
      reproduce the issue. You can add it by placing your save file into a
      ZIP archive and then dragging and dropping the resulting archive file
      into this section.
- type: textarea
  attributes:
    label: Additional info
    placeholder: Submit any additional info (game console output, crash logs, etc) in this section.
