name: Feature request
description: New feature, request or improvement
labels: [ improvement ]

body:
- type: checkboxes
  attributes:
    label: Check for duplicates
    options:
    - label: I checked that there aren't other open issues on the same topic
      required: true
- type: textarea
  attributes:
    label: Describe the problem requiring a solution
    placeholder: >
      Provide a clear and concise description of what the problem is.
      For example: "I'm always frustrated when ...".
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the possible solution
    placeholder: Provide a clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    placeholder: >
      If possible, provide screenshots to illustrate the topic.
      You can add them by dragging and dropping the image file to this section.
- type: textarea
  attributes:
    label: Additional info
    placeholder: Submit any additional info (game console output, crash logs, etc) in this section.
