LIBS := $(LIBS) -lSDL -lmad -lvorbisfile -lvorbis -logg

ifndef WITHOUT_IMAGE
LIBS := $(LIBS) -lSDL -lpng -ljpeg
endif

ifdef WITH_ICONS
IDICON := 1099
CFLAGS := $(CFLAGS) -DID_ICON=$(IDICON)
export IDICON
endif

AR := i686-w64-mingw32-ar
CXX := i686-w64-mingw32-g++
WINDRES := i686-w64-mingw32-windres
CFLAGS := $(CFLAGS) -O2 -static
LIBS := -static -Wl,-Bstatic $(LIBS) -lwinmm -ldxguid
