PREFIX	= $(DEVKITPRO)/devkitA64/bin/aarch64-none-elf-

CC = $(PREFIX)gcc
CXX = $(PREFIX)g++
AR = $(PREFIX)ar

ARCH = -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE
CFLAGS := $(CFLAGS) $(ARCH) -D__SWITCH__
CXXFLAGS := $(CXXFLAGS) $(ARCH) -D__SWITCH__
CFLAGS_TP := $(CFLAGS_TP) $(ARCH)
CXXFLAGS_TP := $(CXXFLAGS_TP) $(ARCH)

LIBS := $(LIBS) -lSDL2 -lfreetype -lbz2 -lvorbisidec -lmodplug -lmpg123 -lm -lopusfile -logg -lopus -ljpeg -lwebp -specs=$(DEVKITPRO)/libnx/switch.specs
