ifndef WITHOUT_MIXER
LIBS := $(LIBS) -lSDL -lmad -lvorbisfile -lvorbis -logg
endif

ifndef WITHOUT_UNICODE
LIBS := $(LIBS) -lfreetype
endif

ifdef WITH_ICONS
IDICON := 1099
CFLAGS := $(CFLAGS) -DID_ICON=$(IDICON)
export IDICON
endif

AR := arm-mingw32ce-ar
CXX := arm-mingw32ce-g++
WINDRES := arm-mingw32ce-windres
CFLAGS := $(CFLAGS) -ffunction-sections -DWITHOUT_MOUSE -static
LIBS := -Wl,-Bstatic $(LIBS) -lmmtimer
LDFLAGS := -static $(LDFLAGS) -Wl,--gc-sections
