name: Code style check

on: [pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: run clang-format-diff
      run: bash ./script/tools/check_code_format.sh
