name: Lint website

on:
  workflow_call:
    inputs:
      paths:
        description: 'Paths to check for changes'
        required: false
        type: string
        default: 'docs/**/*.{html,scss,js}'

jobs:
  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{html,scss}
