name: Linux (release)

on:
  push:
    branches: [ master ]

jobs:
  sdl1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: install SDL 1
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl1.2-dev libsdl-ttf2.0-dev libsdl-mixer1.2-dev libsdl-image1.2-dev gettext
    - name: compile
      run: make -j 2
      env:
        FHEROES2_SDL1: "ON"
        FHEROES2_STRICT_COMPILATION: "ON"
    - name: create package
      run: |
        cp doc/README.txt .
        zip fheroes2_ubuntu_sdl1.zip fheroes2 LICENSE fheroes2.key script/linux/install_sdl_1.sh script/demo/demo_linux.sh changelog.txt README.txt
    - uses: ncipollo/release-action@v1
      with:
        artifacts: fheroes2_ubuntu_sdl1.zip
        body: ${{ github.event.commits[0].message }}
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Ubuntu (Linux) build with SDL 1.2 support (latest commit)
        tag: fheroes2-linux-sdl1_dev
        allowUpdates: true
        prerelease: true
        replacesArtifacts: true
  sdl2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: install SDL 2
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev gettext
    - name: compile
      run: make -j 2
      env:
        FHEROES2_STRICT_COMPILATION: "ON"
    - name: create package
      run: |
        cp doc/README.txt .
        zip fheroes2_ubuntu_sdl2.zip fheroes2 LICENSE fheroes2.key script/linux/install_sdl_2.sh script/demo/demo_linux.sh changelog.txt README.txt
    - uses: ncipollo/release-action@v1
      with:
        artifacts: fheroes2_ubuntu_sdl2.zip
        body: ${{ github.event.commits[0].message }}
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Ubuntu (Linux) build with SDL 2.0 support (latest commit)
        tag: fheroes2-linux-sdl2_dev
        allowUpdates: true
        prerelease: true
        replacesArtifacts: true
