name: Push

on:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    name: Android
    uses: ./.github/workflows/android.yml
    secrets:
      ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
  make:
    name: Make
    uses: ./.github/workflows/make.yml
  msvc:
    name: MSVC
    uses: ./.github/workflows/msvc.yml
  sonarcloud:
    name: SonarCloud Analyzer
    uses: ./.github/workflows/sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  translation:
    name: Translation update
    needs:
    - android
    - make
    - msvc
    uses: ./.github/workflows/translation_update.yml
