name: Push

on:
  push:
    branches: [ master ]

jobs:
  make:
    name: Make
    uses: ./.github/workflows/make.yml

  msvc:
    name: MSVC
    uses: ./.github/workflows/msvc.yml

  sonarcloud:
    name: SonarCloud Analyzer
    uses: ./.github/workflows/sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
