name: VS2019

on:
  pull_request:
    branches: [ master ]

jobs:
  sdl1:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: install SDL 1
      run: |
        cd script/windows
        ./install_packages.bat
        cd ../..
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: compile
      run: MSBuild.exe fheroes2-vs2019.vcxproj /property:Configuration=Release-SDL1 /property:Platform=x64
