name: VS2019

on:
  pull_request:
    branches: [ master ]

jobs:
  sdl1:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: install SDL 1
      run: |
        cd script/windows
        ./install_packages.bat
        cd ../..
    - name: compile
      run: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe fheroes2-vs2019.vcxproj /property:Configuration=Release-SDL1 /property:Platform=x64
