name: VS2019

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config-type: [Release-SDL1, Release-SDL2]
        platform-type: [x86, x64]
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: install packages
      run: |
        cd script/windows
        ./install_packages.bat
        cd ../..
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: compile
      run: MSBuild.exe fheroes2-vs2019.vcxproj /property:Configuration=${{ matrix.config-type }} /property:Platform=${{ matrix.platform-type }}
